### ISSUE TITLE
Authorization service needs to be added?

### ISSUE THREAD

**Issue by damirsharip** [meysamhadeli/shop-golang-microservices#78]
I am new in microservices and starting with your project to understand it. Thank you very much. But when starting to deploy your project on my device. I started getting issues, for example, services wants authorization, but I do not have authorization am I right?

**Comment by meysamhadeli** [comment]
Hi,
I hope this project was helpful for you :)
Yes, for access to each endpoint, you need to have a valid token.
You can get a valid token with Token endpoint in shop.rest file. After getting a valid token, you can pass this valid token as authorization header and access to endpoints.
For simple using of project you can use shop.rest and I simulate most of the endpoint of project in this file, and you can call It easily. (for using .rest file, you need to install rest client in vscode or goland)
