### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by lexuanquynh** [meysamhadeli/shop-golang-microservices#79]
The project looks good. However, I can't find any instructions on how to use the API.
How do I build and deploy?

**Comment by meysamhadeli** [comment]
> The project looks good. However, I can't find any instructions on how to use the API. How do I build and deploy?

Hi, Thanks for your feedback.
I added documentation for building, running and testing the application. Also, I added an API documentation for testing APIs easily.

**Comment by lexuanquynh** [comment]
Thank you for your support.
Projects like this are great for educating backend beginners like me.
Best regards.
