### ISSUE TITLE
Does this application support database backup?

### ISSUE THREAD

**Issue by lexuanquynh** [meysamhadeli/shop-golang-microservices#84]
Does this application support database backup?
If so, how will it be done?

**Comment by meysamhadeli** [comment]
No, it doesn't support it. We usually do it in our database and DBA creates a job for doing this.

**Comment by lexuanquynh** [comment]
@meysamhadeli 
Thank you for your response.
My personal question is that when I add a unique value to Email, I can't seem to migrate it.
Please let me know how to fix it.
```bash
	Email     string    `json:"email" gorm:"unique;not null"`
```

**Comment by meysamhadeli** [comment]
> @meysamhadeli Thank you for your response. My personal question is that when I add a unique value to Email, I can't seem to migrate it. Please let me know how to fix it.
> 
> ``` shell
> 	Email     string    `json:"email" gorm:"unique;not null"`
> ```

You're welcome :)
I am not advanced in gorm. But you can follow the documentation of Gorm to fix this issue. In the documentation mention to email property and other usage of constraints. 
You can find it here: [https://v1.gorm.io/docs/models.html#Declaring-Models](https://v1.gorm.io/docs/models.html#Declaring-Models)
