### ISSUE TITLE
Is the user creation API ready?

### ISSUE THREAD

**Issue by lexuanquynh** [meysamhadeli/shop-golang-microservices#85]
When trying to call the API create user.
However, i got the 401 error.
Is the API currently available?
I am very interested in this project. Hope you can help.
```bash
http://localhost:5002/api/v1/users
```

**Comment by lexuanquynh** [comment]
<img width="968" alt="Screenshot 2023-12-24 at 09 47 29" src="https://github.com/meysamhadeli/shop-golang-microservices/assets/17588791/0f0fa654-82c6-45cd-af8c-95a0cace1c19">

**Comment by lexuanquynh** [comment]
I use Postman:

<img width="973" alt="Screenshot 2023-12-24 at 09 52 13" src="https://github.com/meysamhadeli/shop-golang-microservices/assets/17588791/3adddbe9-a7a9-42b9-a99b-146c47b335f7">

**Comment by lexuanquynh** [comment]
I have replace this line:
```bash
group.POST("", createUser(validator, log, ctx), echomiddleware.ValidateBearerToken())
```
-> 
```bash
group.POST("", createUser(validator, log, ctx))
```
It's call OK.
But I'm not sure I truth when did that.

**Comment by meysamhadeli** [comment]
All APIs are protected by JWT and you get a 401 error. in `shop.rest` you can find the Token endpoint call it gets a valid token and uses this valid token as an `Authorization header` in your postman.

**Comment by meysamhadeli** [comment]
> I have replace this line:
> 
> ```shell
> group.POST("", createUser(validator, log, ctx), echomiddleware.ValidateBearerToken())
> ```
> 
> ->
> 
> ```shell
> group.POST("", createUser(validator, log, ctx))
> ```
> 
> It's call OK. But I'm not sure I truth when did that.

We need `echomiddleware.ValidateBearerToken()` because we want to protect our API with JWT.

**Comment by lexuanquynh** [comment]
@meysamhadeli 
Thanks for taking the time to answer my questions.
I just migrated to Golang and have a lot to learn.
Best regards and I look forward to hearing from you.

**Comment by meysamhadeli** [comment]
> @meysamhadeli Thanks for taking the time to answer my questions. I just migrated to Golang and have a lot to learn. Best regards and I look forward to hearing from you.

You're welcome :) I hope this repo was helpful for you ;)

**Comment by dtherhtun** [comment]
In the provided [function](https://github.com/meysamhadeli/shop-golang-microservices/blob/719450af495a670516ece459b65e7d70ae8fbf6d/internal/pkg/http/echo/middleware/validate_token_middleware.go#L14), I noticed that token validation is not done against the OAuth server endpoint {{identity-api}}/validate-token. Could you please explain the reasoning behind this choice or clarify the token validation strategy used in this context?

**Comment by meysamhadeli** [comment]
> In the provided [function](https://github.com/meysamhadeli/shop-golang-microservices/blob/719450af495a670516ece459b65e7d70ae8fbf6d/internal/pkg/http/echo/middleware/validate_token_middleware.go#L14), I noticed that token validation is not done against the OAuth server endpoint {{identity-api}}/validate-token. Could you please explain the reasoning behind this choice or clarify the token validation strategy used in this context?

I just followed the documentation of library: [go-oauth2/oauth2](https://github.com/go-oauth2/oauth2)
